### ISSUE TITLE
Plug IP

### ISSUE THREAD

**Issue by CAOLINAN** [rodneymo/rig-monitor#1]
Hello,rodneymo .
 I want to build this project.But I can't understand the pug IP in the rig-monitor.conf.Is that a gateway?Or other things.Thank you!

**Comment by rodneymo** [comment]
The plug IP is in case you want to monitor the power consumption on your rigs like in my diagram. Those are optional (http://www.tp-link.com/us/products/details/cat-5516_HS110.html). If you are not planning to use them then just disable them and leave the field empty like this:
'riglx01,192.168.1.88,,6,164,75,1200'
And don't forget to disable them in the config file:
SMART_PLUGS=0

**Comment by CAOLINAN** [comment]
OK.Thank you very much!
