### ISSUE TITLE
Dual Mining on same pool not possible?

### ISSUE THREAD

**Issue by wishbone1138** [rodneymo/rig-monitor#15]
If you dual mine on the same pool (ETH+SIA on nanopool) it will store both values in the DB under nanopool with no distinction between the two.  There probably needs to be a column added in the DB added for coin since some of these pools allow you to mine multiple different coins.

**Comment by rodneymo** [comment]
that should be possible you'd use the label to distinguish between 2 items in the POOL_LIST array. Something like this:

POOL_LIST=(
        'NANOPOOL,ETH,NANO_ETH,https://api.nanopool.org,NOT_USED,<eth address>'
'NANOPOOL,SIA,NANO_SIA,https://api.nanopool.org,NOT_USED,<sia address>'
)

Let me me know if it works for you

**Comment by rodneymo** [comment]
The example above is missing the API TOKEN. Sorry for that. It should look like 

POOL_LIST=(
'NANOPOOL,ETH,NANO_ETH,https://api.nanopool.org,NOT_USED,ebddc2480f81224b793e57f09342335d3fe23948230983d'
'NANOPOOL,SIA,NANO_SIA,https://api.nanopool.org,NOT_USED,ebddc2480f81224b793e57f09342335d3fe23948230983d'
)

Does this work for you?

**Comment by wishbone1138** [comment]
Perfect, I wasn't clear on what that setting was used for but that makes sense.  That works.
