### ISSUE TITLE
Claymore GPU info not processed correctly

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitor#18]
parse_claymore_gpu_info.awk needs to be modified for my system:

        gpu[GPU_INDEX,"MODEL"]=$6
        gpu[GPU_INDEX,"MEMORY"]=$9
        gpu[GPU_INDEX,"PROC"]=$13
Are the correct values on my system. Sample string:
GPU #0: GeForce GTX 1060 6GB, 6144 MB available, 10 compute units, capability: 6.1

Obviously this works differently for your example.
GPU #0: Ellesmere, 8192 MB available, 36 compute units

It might be better to do a more robust regex if the strings change. I don't have enough systems to validate the difference in strings and claymore reporting. There is probably an advanced regex way to do this in AWK but I haven't figured that out yet.

**Comment by wishbone1138** [comment]
Looks like we've got this one fixed, I suggest closing.

**Comment by rodneymo** [comment]
Fixed in 1.2.0
