### ISSUE TITLE
CSV vs Database discussion

### ISSUE THREAD

**Issue by wishbone1138** [rodneymo/rig-monitor#22]
I maintain that the right way to do this is to keep it in the database.  If you need to do upgrades (or want to do backups) you should implement that in the database directly.  If you want this to be able to scale to large number of rigs, then this really is the only choice.

Another option is influxdb (just learned about it).  I'm using it for my smartthings data at the moment.  It is specifically designed to work with metrics and time series data.  It also integrates with grafana quite nicely.  Here are some pros:
You can write to it with HTTP post commands! (easy to get data in from anywhere or local)
Built in retention and compression.
Integrates with grafana much better than mysql in terms of ease of use.
-Way easier to construct metrics with built in functions MADE for time series graphs.  You can do all this in mysql but it's a lot more complex.  There's a lot of selection boxes with influxdb instead of constructing complex sql statements.  (you can still do that if you wish though)

If you're considering at all writing directly to the db and making those changes, it might be worth looking into.  Mysql isn't a bad choice, I just think influx might be more suited to the needs of this project.

**Comment by wishbone1138** [comment]
Info on shell manipulation of influxdb.
https://docs.influxdata.com/influxdb/v0.9/tools/shell/

**Comment by rodneymo** [comment]
When I started I just wanted to use something I was familiar with.
I had a look at the influxdb and indeed seems like a better choice. 

I will give it a go. And get rid of the CSV logic too.

**Comment by wishbone1138** [comment]
I'm pretty excited about influxdb/grafana integration.  It's quite nice.  I like the idea how easy it is to create new "tables" as well.  Makes adding new functions and upgrades a lot quicker.  I'll probably play with it a bit as well but let me know when you have something to test!

**Comment by rodneymo** [comment]
I have just pushed the 1st version of rig-monitor using influxdb. I also dropped to CSV handling so it's pretty simple script.
I have to say I really like the simplicity:
1) no DB schema required
2) easy setup
3) performance (although I have not been able to test it yet)
4) better integration with with grafana (as you mentioned)
5) data retention policies (no need for cleanup.sh)

Once we move all scripts to use influxdb and run it for a while, we should write a post about it

**Comment by wishbone1138** [comment]
Nice!  I'll take a look. I also got EWBF working with influxdb on my influxdb feature branch.  I'll update the issue about my progress there.

I've been thinking about the "schema" (influx technically doesn't use one)  going forward. I'm considering changing the way the data is stored.  Most of these systems are setup to run on multiple GPUs.  Right now we have gpu stats and rig stats tables.  It might make sense to move entirely to a gpu stats table/series across the board.  If you want the total stats for a particular rig all you need to do is sum up all the gpus for that rig.  Claymore does this for you, but grafana could do it on the fly and you'd completely remove an entire series.   If we run into a tool in the future that does not report per gpu, then you would just make one entry for GPUID 0 for that entire rig in the same series.  It seems most these days are reporting stats per gpu.  In addition, I've also added a column for coin.  So you should be able to write a script for any miner that supports an API easily and import it using this.  As the coin changes (or mining script) it will automatically create a new series for that coin per the configuration file.   Rig list could be modified to specify the type of miner and coin that it's mining currently.  The idea here is to be more flexible in the future with multiple different kinds of miners.  I think we may see some changes in what we're mining in the next few months.  The only snag is dual miners.  Perhaps the rig_list could contain an array element for coin type for miners that support more than one coin.   Here's what I've come up with so far.  For any field not supported by the miner, it would just be zero.  In this case fan speed is not reported by EWBF, so those are all zero.

database schema:
```
time                coin gpu_fan gpu_hashrate gpu_id gpu_power gpu_rej_shares gpu_shares gpu_status gpu_temp miner rig_id
----                ---- ------- ------------ ------ --------- -------------- ---------- ---------- -------- ----- ------
1505611272370728495 ZEC  0       561          0      204       0              94         2          72       EWBF  KINKO_NAVI
1505611332733007069 ZEC  0       551          0      196       0              96         2          72       EWBF  KINKO_NAVI
1505611393159134824 ZEC  0       555          0      195       0              96         2          73       EWBF  KINKO_NAVI
1505611453439567342 ZEC  0       555          0      194       0              102        2          73       EWBF  KINKO_NAVI

```

The next schema item is monitoring uptime status.  I'm not sure the best way to do this.  Right now you just write zeros I think when it can't connect?  I was thinking about making it a bit more specific with a separate series that is dedicated to rig health.  Right now it's super simple, but it would also allow calculations of monitoring uptime between values (theoretically, haven't tried yet).  The idea would be to write 0 when you can't connect and 1 when you can.  This could expand into different status values depending on the type of error (can't connect, miner can't connect to pool, gpus all zero, whatever) Right now I'm writing that every time I poll, it may make more sense to do a quick query and only change the value if it's different than your current state.  Just an idea, I'm not married to it, but I really want a separate function that provides health status that could be flexible with various different types of issues depending on how you wanted to set it up.

```
time                online rig_id
----                ------ ------
1505611201811496037 1      KINKO_NAVI

```

I know this was long, just some of the things I've been working on.  I didn't want to just start pushing these to you since it's a pretty big change in the way you are storing data.  Let me know what you think.

**Comment by rodneymo** [comment]
I think reducing the number of time series wherever possible makes sense but it will have some impact on some of the functionality and data duplication. Some  rig-specific measurements e.g. 
- (wall) power consumption collected from the smart plugs would have to be present in all GPU entries
- rig target hashrate (this is useful to compare the rig total hr vs target in a dial/gauge panel)
- mining time
Those values could be moved to the GPU measurement but that would increase the storage space by the number of GPUs present in each rig. So what I suggest it to keep it and "merge" it with the health status you proposed. 
Wrt the coin type, since there are only single or dual miners can we just add another field. Something like:

`<rig name>,<rig ip>, <miner>, <coin>, <dcoin>, <smart plug IP>,<target hr coin>, <target hr dcoin>, <target temp>, <max power>`



we probably should wrap all the miner-specific scripts into a common one which would call the miner specific script depending on the rig conf above.

**Comment by wishbone1138** [comment]
wall power: The idea I had for power was more of a separate environmental series.  That series could track all kinds of things like temp (room, separate rig probes, etc), power, smoke?.  Lots of options here.    A user would have to map their wall plugs to their own rigs in grafana, so it adds an extra configuration step.  This could be stored per rig, but it feels better placed per room/datacenter/area/whatever.  Still thinking on that one.

mining time: EWFB actually gives you a mining time per GPU.  no idea how useful that is, but it does it.  I don't use it but it would be a bummer to leave out data if it's there.

Another interesting note.  Series are created completely dynamically (schemaless).  So technically we can completely leave off columns from miners that do not support that stat and the DB won't even blink.  The integration with grafana picks up what's there without forcing any kind of rigid schema.  Anything with a different tag value creates a different series.  I'm not sure how grafana deals with that if you try to reference a value pair that doesn't exist across all series.  I suppose that would need to be tested, but you could always specify the correct miner tag to get around that (if it was an issue).

So for gpu_stats here is what I'm thinking

```
**Measurement ** 
gpu_stats
**Tag set**
rig_id
miner
coin
gpu_id
**possible field sets**
hashrate
fan
power
rej_shares
status(this is some sort of advanced gpu status in EWFB)
temp
uptime(this is time started in EWFB)
```

I'm debating the info_rig series.  Couldn't you just plug this in manually and easily update it when you want directly in grafana?  Targets for alerting and such can't really be pulled from the database anyway (that I've seen?).  Adding values inline from influxdb into a table is something I haven't figured out..  Just thinking out loud.

Agreed RE: the single master script, that approach makes sense. I still purpose breaking smart plug into it's own section not tied to a specific rig.  Some people maybe run more than one rig off their environmental API (whatever that might be).

**Comment by wishbone1138** [comment]
I'm thinking we should have separate files for pools and miners.  I think that's what you're suggesting already?  Might make development easier.  A single file that figures out what the user wants from the conf file and calls the appropriate script (separate file).  That way we have a plug in system of sorts for development of new pools and miners based on a common output that gets returned to our calling script to write out the data.  Could be dynamic in the calling script to just call pool_$NAME.sh or miner_$NAME.sh.  Make a template and all people have to do is fill in their API calls and format based on the standard.

**Comment by rodneymo** [comment]
@wishbone1138 can we close this one? I think everything has been converted at this point.

**Comment by wishbone1138** [comment]
closed =)
