### ISSUE TITLE
POOL MODULE - MPOS current state?

### ISSUE THREAD

**Issue by wishbone1138** [rodneymo/rig-monitor#34]
Do you use an MPOS pool?  The one I'm testing one does not have some of the attributes you're looking for.  I don't know much about these pools and it could be entirely do to the version of this particular pool.  Have you tested this pool code recently with the latest dev_influxdb code?

**Comment by rodneymo** [comment]
yes. I have tested it and it works with miningpoolhub.
Which pool are you using and which APIs are not working?

**Comment by wishbone1138** [comment]
I'm using on a coin called Defcoin, it's not worth anything and it's just for fun/testing.  The pool is on SECDSM but honestly I'm guessing it's just an older version.  I wouldn't worry to much about it if it works on the pools you use.  The coin can't be looked up on the coin lookup either so if I want to use it I'll probably have to do something custom for it anyway.  No worries, I don't think this represents a normal MPOS pool so I'll close this out.
