### ISSUE TITLE
CONF FILE - NEW GLOBALS

### ISSUE THREAD

**Issue by wishbone1138** [rodneymo/rig-monitor#35]
I think we need new globals for database name and database ip in our conf file?  I'm not sure if anyone else needs that, but I could certainly use an easy way to move between databases for testing at the moment.

**Comment by rodneymo** [comment]
agreed. Let's keep this open until we add it.

**Comment by rodneymo** [comment]
Implemented.
See here: https://github.com/rodneymo/rig-monitor/commit/3e6e02d832c885ee8d430cd7693bc1f86f09b19a
