### ISSUE TITLE
Single influx write per master script

### ISSUE THREAD

**Issue by rodneymo** [rodneymo/rig-monitor#39]
Minimize to number of writes per script by moving http post to master script e.g. rig-monitor.sh instead of individual writes per miner script

**Comment by wishbone1138** [comment]
I like it.  Perhaps we go back to temp files for this in order to make sure our variables don't exceed the max.

**Comment by rodneymo** [comment]
Implemented. 
https://github.com/rodneymo/rig-monitor/commit/3aefb051d501a3a1f8123eaf2694e699b0399b6f
