### ISSUE TITLE
no temperature and fan reporting for GPU10 11 12

### ISSUE THREAD

**Issue by invidtiv** [rodneymo/rig-monitor#57]
So I cannot get any value on any machine that has 11 or more GPU.
the temp value and fan value is always 0 0 for GPU10 GPU 11 and GPU12.

**Comment by Vladislav-Ilcheff** [comment]
I have a solution for this, but I can't fix it for dual mining as I don't dual mine. 
I will need some assistance with making in work as it should for dual mining.

**Comment by invidtiv** [comment]
I don t dual mine, so if you could share the solution, I would apreciate it.
I open to try and find a solution for dual mining

**Comment by Vladislav-Ilcheff** [comment]
I still have a bit work to do on it... I thought it is OK... but it is not... I will share for sure, when i fix it... 

EDIT:  All works, except that incorrect and rejected shares are both counted as incorrect(I'll try to fix this as well in few days).
I will test it in my monitoring just to test if it works OK 

EDIT 2: Here is link https://cloud.kochinata.eu/s/Dtp2req352Yz4r3

Replace this file with rig-monitor/awk/parse_claymore_status.awk
But first make a backup of original file just in case...

Here is a screenshot after modifications: https://cloud.kochinata.eu/s/Ei4RwWH5N5SyL2k 

I will make a fork later to include the file in repo

**Comment by invidtiv** [comment]
Thank you, it works like a charm, I am changing a bit the sql struture , 
from having on both gpu tables
rig_gpu_id | varchar(12)
to having
rig_name | varchar(10)
rig_gpu_id | tinyint
and increased the size to make room for Rx580 description
model | varchar(40)
I have been messing a lot, since I never managed to get your panels running in grafana. And have been setting up my own panels.
since I do SQL server Mysql isn t far and quite easy to do.

I will not push or create commits because it would break your grafana panels for sure. But for me it help me a lot on sorting and analysis.

I need to try and master your awk skills, then I could help you, increase even some data, on the pools data for each miner.
And also get a weather update for my location, since it affect a lot Watt and MH/s. If I could get temp, humidity, that would help me get some more data.
I m sorry for taking long to close this issue.
Thank you.

It is a shame I never got your panels to work....
