### ISSUE TITLE
NANOPOOL - Worker List

### ISSUE THREAD

**Issue by hobojoe720** [rodneymo/rig-monitor#58]
I have edited the NANOPOOL dashboard to monitor Eth, and there are 2 graphs for Shares and Active Workers. 
Shares isnt actually configured, and the Active Workers is configured for eithermine. I have checked the database and the pool-monitor.sh scripts and it looks like Active Workers isnt pulled in for Nano Pool.

Could this be added please.

**Comment by rodneymo** [comment]
Support for nano pool shares has been added in the newest version 2.0. See here: http://randomcryptostuff.blogspot.nl/2018/05/new-version-20beta1-installation.html
