### ISSUE TITLE
Support for Wemo plugs

### ISSUE THREAD

**Issue by rlambert27** [rodneymo/rig-monitor#60]
Hello, would be nice to have support for the Wemo plugs.

**Comment by rodneymo** [comment]
Hi,
which model are you using?

**Comment by rlambert27** [comment]
This one here : https://www.amazon.ca/gp/product/B00EOEDJ9W/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

Seems to be model : F7C029fc

**Comment by rodneymo** [comment]
Thanks. I already ordered one. I should have in the next couple of days.
Support for it will be added in v2.1

**Comment by rodneymo** [comment]
Hi,

support for demo plugs has been added to the version 2.2_development_2. You can find it here: https://github.com/rodneymo/rig-monitorv2/releases/tag/2.2.d.2

This feature will be included in the final 2.2 version in 1-2 weeks' time
