### ISSUE TITLE
Problem last steps.

### ISSUE THREAD

**Issue by fraxi12** [rodneymo/rig-monitor#62]
Hi, 
Will somebody please record a video tutorial how install this, but i stay in steps:
"
August 27, 2017
UPDATE: INSTALLATION INSTRUCTIONS - VERSION 1.2
 

The latest version (1.2) of rig-monitor adds the following features:
Support for claymore single and dual mining mode
Integration with ethermine pool (currentStats, payouts) API
Integration with MPOS-based pools (e.g. miningpoolhib) pool (getdashboarddata) API
Integration with nanopool API (generalinfo, payments). Supports all crypto pools (ETH, ETC, SIA, PASC, XMR and ZEC)
Integration with coinmarketcap API for monitoring crypo prices in different quote currencies, trading volume and market cap. Supports conversion to different quote currencies.
Revised template dashboards

Here are the installation steps:
PRE-REQUISITES
Mining rigs
  Rigs running Claymore's miner (tested with 9.6+ versions). Both Windows and Linux are supported.
  Remote manangment port enabled. This option is enabled (READONLY) and running on port 3333 by default.
Management server
linux server (I am using a rasbperry pi version B with 512Mb RAM and a 4Gb SD). If you want to manage 10+ rigs with a data retention longer than 1-2 days then I suggest to user a more power raspberry pi or server)
msysql
grafana-server 4.3.x or 4.4.x (for raspberry pi linux get it here or here for x86 distros)
rig-monitor (my scripts. See below)
Other
TP Link HS110 smart plugs (optional) installed and configured.
admin access to the internet gateway of your rig farm (this is needed to access the raspberry pi remotely via SSH)
INSTALLATION
Update and upgrade installed packages

sudo apt-get update
sudo apt-get upgrade

Install dependencies

sudo apt-get install mysql-server
sudo apt-get install w3m
sudo apt-get install jq

Don't forget to write down mysql's root password

Download and install grafana server

The link below is for raspberry pi v1 (version 4.3.2), for other versions download it from here or here for x86 distros).

wget https://github.com/fg2it/grafana-on-raspberry/releases/download/v4.3.2/grafana_4.3.2_armhf.deb
sudo dpkg -i grafana_4.3.2_armhf.deb 
sudo apt-get install -f

Configure grafana server

Edit  /etc/grafana/grafana.ini with your favorite editor. 
There are lots of options there, but you should, at least enable the ones bellow:

Under the [paths] section uncomment the following lines

data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins

Under the [server] section uncomment the following lines

protocol = http
http_port = 3000

Under the [database] section uncomment the following lines. Grafana needs to store it's metadata in a database. It comes with sqlite, which I am going to use. Alternatively you could configure it to use mysql if you wish.

type = sqlite3

Under the [security] section uncomment the following lines

admin_user = adminadmin_password = admin

Under the [auth.basic] section uncomment the following lines

enabled = true

Start grafana-server

sudo service grafana-server start

Check if server is running

sudo service grafana-server status

Check if grafana UI is running properly. Open web browser and enter grafana web server URL: http://<management server IP>:3000

Enable startup on boot

sudo update-rc.d grafana-server defaults

In case the service doesn't start automatically after boot you can fix it by running

sudo systemctl enable grafana-server.service "

ok grafana starting next i must copy rig-monitor to 'grafana' ?

sry my eng.

**Comment by rodneymo** [comment]
Hi,
v1.2 is no longer supported. Please try the newest version. http://randomcryptostuff.blogspot.nl/2018/05/new-version-20beta1-installation.html
